### ISSUE TITLE
openHAB problems if CometVisu is running (PaperUI and HabPanel stop working)

### ISSUE THREAD

**Issue by kasi0815** [CometVisu/CometVisu#916]
Hi all, I’m new here but working with Homematic and OpenHAB for some time already. Now I look for a good visualization and decided for CometVisu. But any time I start CometVisu (visualization and PHP - via PaperUI or adding it to the addons.cfg) I cannot acces PaperUI and HabPanel anymore. OpenHAB seems working and I can operate and edit in CometVisu. But simply looking up for things in paperUI is not possible.

After uninstalling both modules (CometVisu Backend, PHP support for CometVisu) and restarting openHAB, openHAB is working normal. I also completely reinstalled openHAB and CometVisu resulting in the same problem. Cleaning the cache of openHAB also did not help (openhab-cli clean-cache).

My versions:
openHAB 2.4.0-1 (Release Build) on openHABianPi
CometVisu 0.11.0 (same problem with 0.10.x)

**Comment by peuter** [comment]
Can you provide an excerpt from the openHAB log. There must be some errors in there. There has been an error where the cometvisu backend did break the paper-ui. But that has been fixed a long time ago.
You can also skip the PHP-addon for basic testing, its only needed for some advanced features, just to rule out if that bundle causes the problem.

**Comment by kasi0815** [comment]
Sorry. There is no unusual error in the openHAB log (derived from "openHAB 2 Log Viewer).

**Comment by kasi0815** [comment]
Here it is. The errors inside are coming from the still open cometvisu-demo tabs in my browser. I think (hope) that they are not the cause.

2019-03-26 23:58:42.266 [INFO ] [etvisu.internal.servlet.CometVisuApp] - Started CometVisu UI at /cometvisu serving /var/www.0.11.0/cometvisu/

2019-03-26 23:58:44.954 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/9' could not be found in the item registry

2019-03-26 23:58:44.960 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/1' could not be found in the item registry

2019-03-26 23:58:44.964 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/2' could not be found in the item registry

2019-03-26 23:58:44.968 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/20' could not be found in the item registry

2019-03-26 23:58:44.973 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/5' could not be found in the item registry

2019-03-26 23:58:44.976 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/105' could not be found in the item registry

2019-03-26 23:58:44.982 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/16' could not be found in the item registry

2019-03-26 23:58:44.986 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/10' could not be found in the item registry

2019-03-26 23:58:44.990 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/100' could not be found in the item registry

2019-03-26 23:58:44.993 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/50' could not be found in the item registry

2019-03-26 23:58:44.996 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/51' could not be found in the item registry

2019-03-26 23:58:45.000 [ERROR] [etvisu.internal.backend.ReadResource] - Item '12/7/52' could not be found in the item registry

==> /var/log/openhab2/events.log <==

2019-03-26 23:58:45.288 [thome.event.ExtensionEvent] - Extension 'ui-cometvisu-php' has been installed.

2019-03-26 23:58:45.294 [thome.event.ExtensionEvent] - Extension 'ui-cometvisu' has been installed.

==> /var/log/openhab2/openhab.log <==

2019-03-26 23:58:46.142 [ERROR] [etvisu.internal.backend.ReadResource] - Item '0/0/0' could not be found in the item registry

==> /var/log/openhab2/events.log <==

2019-03-26 23:59:00.036 [ome.event.ItemCommandEvent] - Item 'VAR_DewPointDiff' received command REFRESH

2019-03-26 23:59:00.049 [ome.event.ItemCommandEvent] - Item 'VAR_DewPointHit' received command REFRESH

2019-03-26 23:59:00.070 [ome.event.ItemCommandEvent] - Item 'VAR_MuelltonneRaus' received command REFRESH

==> /var/log/openhab2/openhab.log <==

2019-03-26 23:59:00.119 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name '${sysVarPresence}' contains invalid characters, new Datapoint name '__sysVarPresence_'

2019-03-26 23:59:00.149 [WARN ] [ematic.handler.HomematicThingHandler] - Datapoint 'GWE00000000:2#M_llTonne-anzeigen' not found on gateway '3014F711A061A7D70992B840'

2019-03-26 23:59:00.155 [WARN ] [ematic.handler.HomematicThingHandler] - Datapoint 'GWE00000000:2#BadL_fter_EIN_Schalten' not found on gateway '3014F711A061A7D70992B840'

2019-03-26 23:59:00.160 [WARN ] [ematic.handler.HomematicThingHandler] - Datapoint 'GWE00000000:2#BadL_fter_AUS_Schalten' not found on gateway '3014F711A061A7D70992B840'

2019-03-26 23:59:00.199 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name '${sysVarPresence}' contains invalid characters, new Datapoint name '__sysVarPresence_'

2019-03-26 23:59:00.217 [WARN ] [ematic.handler.HomematicThingHandler] - Datapoint 'GWE00000000:2#M_llTonne-anzeigen' not found on gateway '3014F711A061A7D70992B840'

2019-03-26 23:59:00.222 [WARN ] [ematic.handler.HomematicThingHandler] - Datapoint 'GWE00000000:2#BadL_fter_EIN_Schalten' not found on gateway '3014F711A061A7D70992B840'

2019-03-26 23:59:00.225 [WARN ] [ematic.handler.HomematicThingHandler] - Datapoint 'GWE00000000:2#BadL_fter_AUS_Schalten' not found on gateway '3014F711A061A7D70992B840'

2019-03-26 23:59:00.262 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name '${sysVarPresence}' contains invalid characters, new Datapoint name '__sysVarPresence_'

2019-03-26 23:59:00.273 [WARN ] [ematic.handler.HomematicThingHandler] - Datapoint 'GWE00000000:2#M_llTonne-anzeigen' not found on gateway '3014F711A061A7D70992B840'

2019-03-26 23:59:00.277 [WARN ] [ematic.handler.HomematicThingHandler] - Datapoint 'GWE00000000:2#BadL_fter_EIN_Schalten' not found on gateway '3014F711A061A7D70992B840'

2019-03-26 23:59:00.282 [WARN ] [ematic.handler.HomematicThingHandler] - Datapoint 'GWE00000000:2#BadL_fter_AUS_Schalten' not found on gateway '3014F711A061A7D70992B840'

**Comment by peuter** [comment]
The " Item '???' could not be found in the item registry" errors are normal and no problem.

**Comment by kasi0815** [comment]
I just rebooted with "CometVisu Backend" but without "PHP support for CometVisu" and it seems working well. This is pity as I created my cometvisu with the editor.

**Comment by kasi0815** [comment]
This is strange. Now after just some minutes testing, PaperUI and HabPanel first slowed down and now it seems they stoped working (same problem as above when running the PHP module).

**Comment by peuter** [comment]
Sorry I don't know how to help, when there are no error messages and I don't have that problem. Maybe some kind of performance issue? Does the load increase on your raspberry?

**Comment by kasi0815** [comment]
The load is <<10% and the memory also seems to be ok. Now after 12h running without operations on my side, CometVisu is not responing in Firefox but no error. If I call CometVisu in the Internet Explorer then I get this errors:

TypeError: Unable to get property 'length' of undefined or null reference
   at statics.add.native (http://192.168.178.51:8080/cometvisu/script/cv-mshtml.js:213:289241)
   at members.parseXML (http://192.168.178.51:8080/cometvisu/script/cv-mshtml.js:213:275010)
   at members.bootstrap (http://192.168.178.51:8080/cometvisu/script/cv-mshtml.js:213:1085779)
   at members._checkQueue (http://192.168.178.51:8080/cometvisu/script/cv-mshtml.js:213:1097942)
   at Anonymous function (http://192.168.178.51:8080/cometvisu/script/cv-mshtml.js:213:1096652)
   at h (http://192.168.178.51:8080/cometvisu/script/cv-mshtml.js:213:149097)
   at Anonymous function (http://192.168.178.51:8080/cometvisu/script/cv-mshtml.js:213:159529)
   at statics.then (http://192.168.178.51:8080/cometvisu/script/cv-mshtml.js:213:160009)
   at Anonymous function (http://192.168.178.51:8080/cometvisu/script/cv-mshtml.js:213:159496)
   at members.dispatchEvent (http://192.168.178.51:8080/cometvisu/script/cv-mshtml.js:213:159401)

**Comment by kasi0815** [comment]
Just to inform: the problem still exists. It seems to me that it is a performance problem (some messages stuck somewhere?) on the PI. This dedicated PI3+ is running opneHab and CometVisu. There are just "Loaded 39 openHAB items", so should be ok. However, the current situation is, if I do not touch the system for quite a while then I can operate CometVisu. If I continue developing the ComeVisu pages then after about 20 to 30 mins I run into same problems.
Because I do not know how to monitor which resources of openHab and CometVisu, I cannot followup at this time but will monitor and see later...

**Comment by peuter** [comment]
As I mentioned before I would try to get rid of the PHP-Addon on your productive system. If you really need the extra features it provides like the XML-Editor you might by able to use an extra Webserver with PHP support and develop you pages there and just copy them to the "real" system if you are done. Maybe it helps.

**Comment by kasi0815** [comment]
OK, will try and monitor. Thanks.

**Comment by peuter** [comment]
PHP Addon is obsolete now. The recommended way is to use an extra webserver with PHP support, as alternative the openHAB-cv backend has a native Java implementation of the backend php code.
